language: ru

pipeline:
  - name: SpacyNLP
    model: "ru_core_news_md"

  - name: SpacyTokenizer

  - name: SpacyFeaturizer

  - name: RegexFeaturizer

  - name: CountVectorsFeaturizer
    analyzer: "word"

  - name: CountVectorsFeaturizer
    analyzer: "char_wb"
    min_ngram: 1
    max_ngram: 4

  - name: DIETClassifier
    epochs: 100
    constrain_similarities: true
    random_seed: 42

  - name: EntitySynonymMapper

  - name: FallbackClassifier
    threshold: 0.3
    ambiguity_threshold: 0.1

  - name: ResponseSelector
    epochs: 30
    constrain_similarities: true

policies:
  - name: MemoizationPolicy
    max_history: 5

  - name: RulePolicy

  - name: TEDPolicy
    max_history: 5
    epochs: 50
    constrain_similarities: true
